-- V0.x: BC 네임스페이스(session, key, federation) 준비 및 sso_readonly 읽기 권한
CREATE SCHEMA IF NOT EXISTS session;
CREATE SCHEMA IF NOT EXISTS key;
CREATE SCHEMA IF NOT EXISTS federation;

GRANT USAGE ON SCHEMA session TO sso_readonly;
GRANT USAGE ON SCHEMA key TO sso_readonly;
GRANT USAGE ON SCHEMA federation TO sso_readonly;

GRANT SELECT ON ALL TABLES IN SCHEMA session TO sso_readonly;
GRANT SELECT ON ALL TABLES IN SCHEMA key TO sso_readonly;
GRANT SELECT ON ALL TABLES IN SCHEMA federation TO sso_readonly;

GRANT SELECT ON ALL SEQUENCES IN SCHEMA session TO sso_readonly;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA key TO sso_readonly;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA federation TO sso_readonly;

ALTER DEFAULT PRIVILEGES IN SCHEMA session GRANT SELECT ON TABLES TO sso_readonly;
ALTER DEFAULT PRIVILEGES IN SCHEMA key GRANT SELECT ON TABLES TO sso_readonly;
ALTER DEFAULT PRIVILEGES IN SCHEMA federation GRANT SELECT ON TABLES TO sso_readonly;

ALTER DEFAULT PRIVILEGES IN SCHEMA session GRANT SELECT ON SEQUENCES TO sso_readonly;
ALTER DEFAULT PRIVILEGES IN SCHEMA key GRANT SELECT ON SEQUENCES TO sso_readonly;
ALTER DEFAULT PRIVILEGES IN SCHEMA federation GRANT SELECT ON SEQUENCES TO sso_readonly;
